// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using ML_BoligPortalML.Model;

namespace ML_BoligPortalML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            var sampleData = new List<ModelInput>
            {
                new ModelInput
                {
                    PropertyType = @"Apartment",
                    Rooms = 2F,
                    Furnished = false,
                    Elevator = true,
                    Parking = false,
                    Size = 61F,
                    Floor = 2,
                    District = "I. Christensens Gade, 8220 Aarhus"
                }
            };

            foreach (var sample in sampleData)
            {
                // Make a single prediction on the sample data and print results
                var predictionResult = ConsumeModel.Predict(sample);

                Console.WriteLine("Using model to make single prediction -- Comparing actual MonthlyNetRent with predicted MonthlyNetRent from sample data...\n\n");
                Console.WriteLine($"PropertyType: {sample.PropertyType}");
                Console.WriteLine($"Rooms: {sample.Rooms}");
                Console.WriteLine($"Furnished: {sample.Furnished}");
                Console.WriteLine($"Elevator: {sample.Elevator}");
                Console.WriteLine($"Parking: {sample.Parking}");
                Console.WriteLine($"Size: {sample.Size}");
                Console.WriteLine($"Floor: {sample.Floor}");
                Console.WriteLine($"District: {sample.District}");
                Console.WriteLine($"\n\nPredicted MonthlyNetRent: {predictionResult.Score}\n\n");
                Console.WriteLine("=============== End of process, hit any key to finish ===============");
            }
        }
    }
}
