// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ML_BoligPortalML.Model
{
    public class ModelInput
    {
        [ColumnName("District"), LoadColumn(0)]
        public string District { get; set; }


        [ColumnName("PropertyType"), LoadColumn(1)]
        public string PropertyType { get; set; }


        [ColumnName("Rooms"), LoadColumn(2)]
        public float Rooms { get; set; }


        [ColumnName("Furnished"), LoadColumn(3)]
        public bool Furnished { get; set; }


        [ColumnName("Shareable"), LoadColumn(4)]
        public bool Shareable { get; set; }


        [ColumnName("PetsAllowed"), LoadColumn(5)]
        public bool PetsAllowed { get; set; }


        [ColumnName("Elevator"), LoadColumn(6)]
        public bool Elevator { get; set; }


        [ColumnName("SeniorFriendly"), LoadColumn(7)]
        public bool SeniorFriendly { get; set; }


        [ColumnName("StudentOnly"), LoadColumn(8)]
        public bool StudentOnly { get; set; }


        [ColumnName("Balcony"), LoadColumn(9)]
        public bool Balcony { get; set; }


        [ColumnName("Parking"), LoadColumn(10)]
        public bool Parking { get; set; }


        [ColumnName("Size"), LoadColumn(11)]
        public float Size { get; set; }


        [ColumnName("Floor"), LoadColumn(12)]
        public float Floor { get; set; }


        [ColumnName("RentalPeriod"), LoadColumn(13)]
        public float RentalPeriod { get; set; }


        [ColumnName("AvailableFrom"), LoadColumn(14)]
        public string AvailableFrom { get; set; }


        [ColumnName("MonthlyNetRent"), LoadColumn(15)]
        public float MonthlyNetRent { get; set; }


        [ColumnName("Utilities"), LoadColumn(16)]
        public float Utilities { get; set; }


        [ColumnName("Deposit"), LoadColumn(17)]
        public float Deposit { get; set; }


        [ColumnName("PrepaidRent"), LoadColumn(18)]
        public float PrepaidRent { get; set; }


        [ColumnName("MoveInPrice"), LoadColumn(19)]
        public float MoveInPrice { get; set; }


    }
}
